
alias draw='/Applications/draw.io.app/Contents/MacOS/draw.io'


# Functions


# k8s & helm completion
source <(kubectl completion zsh)
#source <(helm completion zsh)
# https://github.com/helm/helm/issues/5046#issuecomment-463576351
source <(helm completion zsh | sed -E 's/\["(.+)"\]/\[\1\]/g')
# source <(minikube completion zsh)

bindkey -v
bindkey -M vicmd '^[[A' history-substring-search-up
bindkey -M vicmd '^[[B' history-substring-search-down
bindkey -M viins '^[[A' history-substring-search-up
bindkey -M viins '^[[B' history-substring-search-down

setopt histignorealldups share_history

autoload -U +X bashcompinit && bashcompinit

complete -o nospace -C /usr/local/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/matt/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/matt/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/matt/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/matt/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# starship prompt
eval "$(starship init zsh)"
