export ZLE_RPROMPT_INDENT=0

export EDITOR=vim
export XDG_CONFIG_HOME="$HOME/.config"
export BUKU_COLORS=FCexd
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=10

# Aliases
alias catimg='img2sixel -p 16 -h 128 '
alias tf=terraform
alias tf-docs='terraform-docs'
alias plith='pluralith'
alias b='buku --np'
alias ll='lsd -l'
alias lla='lsd -la'
alias lst='lsd --tree'
alias lsat='lsd -a --tree'

# Functions
function csdiff () { sdiff -w $(stty size | awk '{print $NF}') $@ | colordiff; }
# Strip final EOL from a file
function chompeol () { printf %s "$(cat $1)" > $1 }
function take() {mkdir -p $@ && cd ${@:$#}}
function ipa () {
  awk '/([0-9]{1,3}\.){3}[0-9]{1,3}/ {
    split($2, ary, /\//)
    ip = ary[1]
    if (ip != "127.0.0.1") {
      print ip
    }
  }' <(ip -4 a)
}

PATH=~/.local/bin:$PATH

eval "$(thefuck --alias fuck)"

# The following lines were added by compinstall
zstyle :compinstall filename "${HOME}/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
# End of lines configured by zsh-newuser-install

# To use bash autocompletions
autoload -U +X bashcompinit && bashcompinit
source "$(brew --prefix)/etc/bash_completion.d/az"

## zplug
# brew install zplug
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
zplug zdharma/fast-syntax-highlighting
zplug zsh-users/zsh-history-substring-search
zplug zsh-users/zsh-autosuggestions
zplug mdumitru/git-aliases
zplug marzocchi/zsh-notify
zplug joel-porquet/zsh-dircolors-solarized
zplug zdharma-continuum/zsh-diff-so-fancy
zplug jimeh/zsh-peco-history

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load #--verbose

# source ${HOME}/git/tmuxinator/completion/tmuxinator.zsh

# k8s & helm completion
source <(kubectl completion zsh)
#source <(helm completion zsh)
# https://github.com/helm/helm/issues/5046#issuecomment-463576351
source <(helm completion zsh | sed -E 's/\["(.+)"\]/\[\1\]/g')
# source <(minikube completion zsh)

setopt histignorealldups share_history

autoload -U +X bashcompinit && bashcompinit

complete -o nospace -C /usr/local/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/matt/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/matt/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/matt/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/matt/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# starship prompt
eval "$(starship init zsh)"
